### ISSUE TITLE
Doesn't install

### ISSUE THREAD

**Issue by berenddeboer** [SungardAS/generator-lambda-formation#1]
Somehow the generator doesn't install. When I do

`sudo npm install -g generator-lambda-formation 
/usr/local/lib
└── generator-lambda-formation@0.1.5`

But 
`yo --help | grep lambda-formation'

does not return anything. There are no errors. Any suggestions? This is on Ubuntu 16.04 with nodejs 4.2.6.

**Comment by berenddeboer** [comment]
Just tried on Ubuntu 14.04, same thing.

`Error lambda-formation:project my-lambda-formation-project
`
`You don't seem to have a generator with the name lambda-formation:project installed.
You can see available generators with npm search yeoman-generator and then install them with npm install [name].
To see the 0 registered generators run yo with the --help option.`

**Comment by kmcgrath** [comment]
@berenddeboer thank you for opening the issue.

I was able to reproduce the problem and fixed it by re-running yeoman's generator-generator on the project.

I've pushed version 0.1.6.  Let me know if it works for you.

**Comment by kmcgrath** [comment]
Closing this issue. If you are still having problems please reach out.
